import fs from 'node:fs';
import path from 'node:path';

/**
 * The brand badge on the public GitHub Pages site (Story 21.1).
 *
 * `yarn icons:check` already gates the SVG's *geometry* — `docs/assets/cardi-mark-inline.svg`
 * is generated by `scripts/build-brand-icons.mjs` and compared byte-for-byte. What nothing
 * gated is everything around it: that the two pages still reference the asset, and that the
 * CSS keeps the two properties the design system rules out.
 *
 * Each assertion here exists because of a specific, observed failure mode:
 *
 * 1. **The markup.** The badge was a hardcoded `MLC` text node until Story 21.1. A bad merge
 *    reverting it would restore working, plausible-looking HTML that simply shows the
 *    pre-rebrand initials next to the new name — and no build step would notice.
 * 2. **No gradient, no shadow.** The Cardì design system is explicit: "warm, flat and
 *    structural. Paper, not glass. No gradients, no drop shadows." The badge carried both
 *    before the rebrand, so re-adding them is a regression toward the old identity rather
 *    than a novel mistake.
 * 3. **The glyph height must not be a bare percentage.** This one actually happened:
 *    `height: 58.6%` was written first and **rendered at 71.9%**. A percentage height on a
 *    grid item in an auto-sized row is CSS-indefinite, so the browser falls back to intrinsic
 *    sizing and resolves the figure against the width instead. It was caught by measuring the
 *    rendered box in a browser — nothing else would have. `calc()` off `--badge-size` is not
 *    subject to that trap.
 *
 * ⚠️ **Comments are stripped before every CSS assertion, and that is load-bearing**, not
 * tidiness: this repo documents its reasoning in place, so the `.brand-mark img` rule's own
 * comment contains the literal string `height: 58.6%` while explaining why it is wrong. A
 * check against the raw text would match the explanation and fail on correct code.
 */
const repoRoot = path.resolve(__dirname, '..');
const read = (...segments: string[]): string =>
  fs.readFileSync(path.join(repoRoot, ...segments), 'utf8');

const MARK_ASSET = 'assets/cardi-mark-inline.svg';
const PAGES = ['index.html', 'privacy-policy.html'] as const;

const stripCssComments = (css: string): string => css.replace(/\/\*[\s\S]*?\*\//g, '');

/**
 * The declarations of one rule, by exact selector. Anchored to the start of a line so that
 * asking for `.brand-mark` cannot return `.brand-mark img`.
 */
function declarationsOf(css: string, selector: string): string {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const body = stripCssComments(css).match(new RegExp(`^${escaped}\\s*\\{([^}]*)\\}`, 'm'))?.[1];
  if (body === undefined) {
    // Losing the rule entirely is itself the regression — fail loudly rather than
    // silently asserting against an empty string, which every check would pass.
    throw new Error(`No \`${selector}\` rule found in docs/style.css`);
  }
  return body;
}

/** The inner markup of the `.brand-mark` element on a page. */
function brandMarkMarkup(html: string): string {
  const inner = html.match(/<span class="brand-mark"[^>]*>([\s\S]*?)<\/span>/)?.[1];
  if (inner === undefined) throw new Error('No `.brand-mark` element found');
  return inner;
}

describe('docs/ brand badge', () => {
  describe.each(PAGES)('%s', (page) => {
    it('renders the generated Cardì mark inside the badge, not text initials', () => {
      const markup = brandMarkMarkup(read('docs', page));

      expect(markup).toContain(`<img src="${MARK_ASSET}"`);
      // The badge is decorative — the adjacent <h1> carries the name — so it must stay
      // out of the accessibility tree rather than announcing a second, redundant label.
      expect(read('docs', page)).toMatch(/<span class="brand-mark"[^>]*aria-hidden="true"/);
    });
  });

  it('ships the asset the pages reference', () => {
    // A `src` pointing at nothing is a 404 on the live site and renders as a blank badge —
    // visible to a human, invisible to every other gate. `icons:check` proves the file matches
    // the mark; this proves the file is where the HTML looks for it.
    expect(fs.existsSync(path.join(repoRoot, 'docs', MARK_ASSET))).toBe(true);
  });

  it('keeps the badge flat — no gradient, no drop shadow', () => {
    const declarations = declarationsOf(read('docs', 'style.css'), '.brand-mark');

    expect(declarations).not.toMatch(/linear-gradient|radial-gradient|conic-gradient/);
    expect(declarations).not.toMatch(/box-shadow/);
  });

  it('sizes the glyph with calc(), never a bare percentage height', () => {
    const declarations = declarationsOf(read('docs', 'style.css'), '.brand-mark img');
    const height = declarations.match(/height:\s*([^;]+);/)?.[1]?.trim();

    expect(height).toBeDefined();
    expect(height).toContain('calc(');
    // The trap: a percentage here resolves against the wrong axis. See the block comment above.
    expect(height).not.toMatch(/^[\d.]+%$/);
  });
});
