import React from 'react';
import { View } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';

import { useTheme } from '@/shared/theme';

import CardiMark from '@/assets/images/cardi-mark-adaptive.svg';

const MARK_SIZE = 36;

/**
 * The app's own mark, above the auth forms.
 *
 * This used to be `card-account-details-outline` from MaterialCommunityIcons —
 * a stock glyph standing in for an identity that did not exist yet. It is now
 * the real mark, generated by `yarn icons:build` from the same geometry as
 * `icon.png` and the launch surface, so the three cannot drift apart.
 *
 * `cardi-mark-adaptive.svg` draws its stem in `currentColor`, which react-native-svg
 * resolves from the `color` prop. Passing `theme.primary` keeps this exactly as
 * theme-driven as the glyph it replaces — including through the app-wide colour
 * migration, which is a separate change and has not happened yet, so `primary` is
 * still the pre-rebrand blue. The beam stays brand yellow in both schemes: it is
 * the signature, and it is the one thing in the system that never themes.
 */
export const AppIconHeader = () => {
  const { theme } = useTheme();

  return (
    <View
      testID="auth-app-icon-circle"
      style={[styles.circle, { backgroundColor: `${theme.primary}1A` }]}
    >
      <CardiMark
        testID="auth-app-icon"
        width={MARK_SIZE}
        height={MARK_SIZE}
        color={theme.primary}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  circle: {
    marginBottom: 48,
    height: 80,
    width: 80,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 9999
  }
});
