import React from 'react';
import { View } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';

// From the leaf token module, NOT the `@/shared/theme` barrel: several suites
// replace that barrel wholesale with a `useTheme`-only mock, so any static
// token imported through it is `undefined` at render time. `AppLaunchScreen`
// avoids the barrel for the same reason. `useTheme` still comes from the
// barrel, because a test legitimately wants to stub runtime theme state.
import { IDENTITY_COLORS } from '@/shared/theme/tokens.generated';

import CardiMark from '@/assets/images/cardi-mark-inline.svg';

const MARK_SIZE = 40;

/**
 * The app's own mark, above the auth forms.
 *
 * This used to be `card-account-details-outline` from MaterialCommunityIcons —
 * a stock glyph standing in for an identity that did not exist yet. It is now
 * the real mark, generated by `yarn icons:build` from the same geometry as
 * `icon.png` and the launch surface, so the three cannot drift apart.
 *
 * **The field is ink in both schemes, and that is not a shortcut.** The first
 * version put the mark on a `theme.primary` tint over white and let the stem
 * follow the theme via `currentColor`. Measured, the beam landed at **1.34:1**
 * against that field — the accent that makes the mark "Cardì" was invisible on
 * every auth screen in light mode. The problem is not this component's fill: the
 * beam is only legible on ink (11.53:1, against 1.52:1 on white and 1.33:1 on
 * cream), because the design system uses beam as a FILL carrying dark text, never
 * as a stroke on a light surface. So the mark brings its own ground, exactly as
 * the app icon and the launch surface do.
 */
export const AppIconHeader = () => (
  <View testID="auth-app-icon-circle" style={styles.circle}>
    <CardiMark testID="auth-app-icon" width={MARK_SIZE} height={MARK_SIZE} />
  </View>
);

const styles = StyleSheet.create({
  circle: {
    marginBottom: 48,
    height: 80,
    width: 80,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 9999,
    backgroundColor: IDENTITY_COLORS.ink
  }
});
