import { MaterialIcons, MaterialCommunityIcons } from '@expo/vector-icons';
import React from 'react';
import { View, type ViewStyle } from 'react-native';

import { useTheme } from '@/shared/theme';

import CardiMark from '@/assets/images/cardi-mark-adaptive.svg';

/**
 * A glyph in a tinted circle.
 *
 * With NOTHING passed it renders the app's own mark, generated by
 * `yarn icons:build` from the same geometry as `icon.png` and the launch
 * surface. It used to default to MaterialIcons `credit-card` — a stock glyph
 * standing in for an identity that did not exist yet — and the component's only
 * caller took that default, so the welcome screen was showing someone else's
 * credit card.
 *
 * The `icon`/`communityIcon`/`children` props still work and still win, so this
 * stays a general-purpose circle; only the empty case changed meaning.
 */
type BrandedIconProps = {
  size?: number;
  /** A MaterialIcons name. Omit all three of these to get the Cardì mark. */
  icon?: React.ComponentProps<typeof MaterialIcons>['name'];
  communityIcon?: React.ComponentProps<typeof MaterialCommunityIcons>['name'];
  iconSize?: number;
  testID?: string;
  children?: React.ReactNode;
};

const withAlpha = (hex: string, alpha: string) => `${hex}${alpha}`;

export const BrandedIcon = ({
  size = 100,
  icon,
  communityIcon,
  iconSize = 32,
  testID,
  children
}: BrandedIconProps) => {
  const { theme } = useTheme();

  const circleStyle: ViewStyle = {
    width: size,
    height: size,
    borderRadius: size / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withAlpha(theme.primary, '1A')
  };

  return (
    <View testID={testID} style={circleStyle} accessibilityElementsHidden>
      {children ??
        (communityIcon ? (
          <MaterialCommunityIcons name={communityIcon} size={iconSize} color={theme.primary} />
        ) : icon ? (
          <MaterialIcons name={icon} size={iconSize} color={theme.primary} />
        ) : (
          // `currentColor` for the stem, brand yellow for the beam — see
          // AppIconHeader for why the stem follows the theme and the beam does not.
          <CardiMark width={iconSize} height={iconSize} color={theme.primary} />
        ))}
    </View>
  );
};
