import { MaterialIcons, MaterialCommunityIcons } from '@expo/vector-icons';
import React from 'react';
import { View, type ViewStyle } from 'react-native';

import { useTheme } from '@/shared/theme';
// From the leaf token module, NOT the `@/shared/theme` barrel: several suites
// replace that barrel wholesale with a `useTheme`-only mock, so any static
// token imported through it is `undefined` at render time. `AppLaunchScreen`
// avoids the barrel for the same reason. `useTheme` still comes from the
// barrel, because a test legitimately wants to stub runtime theme state.
import { IDENTITY_COLORS } from '@/shared/theme/tokens.generated';

import CardiMark from '@/assets/images/cardi-mark-inline.svg';

/**
 * A glyph in a tinted circle.
 *
 * With NOTHING passed it renders the app's own mark, generated by
 * `yarn icons:build` from the same geometry as `icon.png` and the launch
 * surface. It used to default to MaterialIcons `credit-card` — a stock glyph
 * standing in for an identity that did not exist yet — and the component's only
 * caller took that default, so the welcome screen was showing someone else's
 * credit card.
 *
 * The `icon`/`communityIcon`/`children` props still work and still win, so this
 * stays a general-purpose circle; only the empty case changed meaning.
 */
type BrandedIconProps = {
  size?: number;
  /** A MaterialIcons name. Omit all three of these to get the Cardì mark. */
  icon?: React.ComponentProps<typeof MaterialIcons>['name'];
  communityIcon?: React.ComponentProps<typeof MaterialCommunityIcons>['name'];
  iconSize?: number;
  testID?: string;
  children?: React.ReactNode;
};

const withAlpha = (hex: string, alpha: string) => `${hex}${alpha}`;

export const BrandedIcon = ({
  size = 100,
  icon,
  communityIcon,
  iconSize = 32,
  testID,
  children
}: BrandedIconProps) => {
  const { theme } = useTheme();
  // `children == null`, not `!children`: the render below uses `children ??`,
  // which falls through only for null/undefined. With `!children`, passing
  // `children={false}` claimed the mark was showing (ink field) while the
  // render emitted `false` — a solid ink circle with nothing in it.
  const showsMark = children == null && !icon && !communityIcon;

  const circleStyle: ViewStyle = {
    width: size,
    height: size,
    borderRadius: size / 2,
    alignItems: 'center',
    justifyContent: 'center',
    // Ink when the MARK is showing: the beam is only legible on ink (11.53:1,
    // against 1.34:1 on the tinted field this used to paint). The tint stays for
    // the Material-glyph path, which has no beam to lose. See AppIconHeader.
    backgroundColor: showsMark ? IDENTITY_COLORS.ink : withAlpha(theme.primary, '1A')
  };

  return (
    <View testID={testID} style={circleStyle} accessibilityElementsHidden>
      {children ??
        (communityIcon ? (
          <MaterialCommunityIcons name={communityIcon} size={iconSize} color={theme.primary} />
        ) : icon ? (
          <MaterialIcons name={icon} size={iconSize} color={theme.primary} />
        ) : (
          // White stem, brand yellow beam, on the ink field above.
          <CardiMark width={iconSize} height={iconSize} />
        ))}
    </View>
  );
};
