/**
 * ⛔ DO NOT ADD `icon:` HERE. The omission is deliberate, and it is not the bug it looks like.
 *
 * The sibling `targets/watch/expo-target.config.js` DOES carry `icon: './AppIcon.png'`, so this
 * file reads like an oversight. It is not. `@bacons/apple-targets` accepts the key for a
 * `watch-widget` target and then does the wrong thing with it: `withIosIcon` branches on
 * `type === "watch"` and nothing else, so a `watch-widget` falls to the `else`, which runs
 * `setIconsAsync` over a hardcoded iphone / ipad / ios-marketing size table. Adding it would
 * regenerate fifteen iOS-idiom PNGs inside a watchOS extension — the exact placeholder set Story
 * 21.3 removed, differing only in being Cardì-coloured rather than `#80FF80` green, which makes
 * the regression HARDER to spot, not easier.
 *
 * And none of it would ship. This target carries no `ASSETCATALOG_COMPILER_APPICON_NAME`, so
 * `actool` compiles the catalogue without `--app-icon` and the built `watchwidget.appex` has no
 * `AppIcon` in its `Assets.car` and no icon key in its `Info.plist` at all. A watchOS widget
 * extension is represented by its containing app's icon.
 *
 * The appiconset that remains is generated by `scripts/build-brand-icons.mjs` — one 1024 in the
 * single-size watchOS form — so it is under `yarn icons:check` rather than under prebuild.
 * `test/watch-icons.test.ts` asserts this key's absence, because a comment alone did not seem
 * enough for something a whole spike went into discovering.
 *
 * @type {import('@bacons/apple-targets/app.plugin').Config}
 */
module.exports = {
  type: 'watch-widget',
  displayName: 'Loyalty Card',
  bundleIdentifier: '.watch.widget',
  deploymentTarget: '10.0',
  frameworks: ['WidgetKit', 'SwiftUI'],
  entitlements: {
    'com.apple.security.application-groups': [
      'group.com.iferoporefi.myloyaltycards.watch-complication'
    ]
  }
};
