/**
 * DO NOT EDIT — generated by Style Dictionary from the DTCG token JSON in tokens/.
 * Run `yarn tokens:build` to regenerate; `yarn tokens:check` guards against drift.
 * Canonical token values live in tokens/*.json (Story 16.4).
 */

export const PRIMARY_COLORS = {
  50: '#E8F1FE',
  100: '#D2E3FC',
  200: '#AECBFA',
  300: '#8AB4F8',
  400: '#669DF6',
  500: '#1A73E8',
  600: '#1967D2',
  700: '#185ABC',
  800: '#174EA6',
  900: '#163A7A'
} as const;

export const CARD_COLORS = {
  blue: '#1A73E8',
  red: '#E2231A',
  green: '#16A34A',
  orange: '#F59E0B',
  grey: '#64748B'
} as const;

export const NEUTRAL_COLORS = {
  white: '#FFFFFF',
  black: '#000000',
  slate50: '#F8FAFC',
  slate100: '#F1F5F9',
  slate200: '#E2E8F0',
  slate300: '#CBD5E1',
  slate400: '#94A3B8',
  slate600: '#475569',
  slate700: '#334155',
  slate900: '#0F172A'
} as const;

export const LIGHT_THEME_COLORS = {
  primary: '#1A73E8',
  primaryDark: '#1967D2',
  background: '#FFFFFF',
  backgroundSubtle: '#F5F5F5',
  surface: '#FFFFFF',
  surfaceElevated: '#F5F5F5',
  textPrimary: '#1F1F24',
  textSecondary: '#66666B',
  textTertiary: '#8F8F94',
  border: '#E5E5EB',
  borderStrong: '#8F8F94',
  success: '#16A34A',
  warning: '#D97706',
  error: '#DC2626',
  info: '#1A73E8',
  link: '#1A73E8'
} as const;

export const DARK_THEME_COLORS = {
  primary: '#4DA3FF',
  primaryDark: '#1A73E8',
  background: '#000000',
  backgroundSubtle: '#0A0A0A',
  surface: '#1C1C1E',
  surfaceElevated: '#2C2C2E',
  textPrimary: '#F5F5F7',
  textSecondary: '#D9D9DE',
  textTertiary: '#99999E',
  border: '#38383A',
  borderStrong: '#636366',
  success: '#22C55E',
  warning: '#F59E0B',
  error: '#F87171',
  info: '#4DA3FF',
  link: '#4DA3FF'
} as const;

export const SPACING = { xs: 4, sm: 8, smMd: 12, md: 16, lg: 24, xl: 32, xxl: 48 } as const;

export const LAYOUT = {
  screenHorizontalMargin: 24,
  contentPadding: 24,
  gridGutter: 12,
  cardAspectRatio: 1.3333333333333333,
  safeAreaTopInsetMin: 16,
  safeAreaBottomInsetMin: 16
} as const;

export const TOUCH_TARGET = { min: 44, watch: 32 } as const;
