/**
 * DO NOT EDIT — generated by Style Dictionary from the DTCG token JSON in tokens/.
 * Run `yarn tokens:build` to regenerate; `yarn tokens:check` guards against drift.
 * Canonical token values live in tokens/*.json (Story 16.4).
 */

export const IDENTITY_COLORS = { ink: '#181824', beam: '#FCCC0C', cream: '#F0F0E8' } as const;

export const CARD_COLORS = {
  blue: '#0C3C84',
  red: '#E42424',
  green: '#0C843C',
  orange: '#FCCC0C',
  grey: '#0C84CC'
} as const;

export const NEUTRAL_COLORS = {
  white: '#FFFFFF',
  black: '#000000',
  slate50: '#F8FAFC',
  slate100: '#F1F5F9',
  slate200: '#E2E8F0',
  slate300: '#CBD5E1',
  slate400: '#94A3B8',
  slate600: '#475569',
  slate700: '#334155',
  slate900: '#0F172A'
} as const;

export const LIGHT_THEME_COLORS = {
  primary: '#181824',
  primaryDark: '#2A2A3A',
  onPrimary: '#FFFFFF',
  background: '#F0F0E8',
  backgroundSubtle: '#E8E8DE',
  surface: '#FFFFFF',
  surfaceElevated: '#F7F7F1',
  textPrimary: '#181824',
  textSecondary: '#55555F',
  textTertiary: '#6B6B63',
  border: '#D6D6CB',
  borderStrong: '#9A9A93',
  success: '#181824',
  warning: '#181824',
  error: '#C41E1E',
  onError: '#FFFFFF',
  info: '#181824',
  link: '#181824'
} as const;

export const DARK_THEME_COLORS = {
  primary: '#FCCC0C',
  primaryDark: '#F0F0E8',
  onPrimary: '#181824',
  background: '#000000',
  backgroundSubtle: '#0C0C12',
  surface: '#181824',
  surfaceElevated: '#20202E',
  textPrimary: '#F0F0E8',
  textSecondary: '#B5B5AB',
  textTertiary: '#8F8F85',
  border: '#3A3A48',
  borderStrong: '#55555F',
  success: '#F0F0E8',
  warning: '#FCCC0C',
  error: '#FF453A',
  onError: '#181824',
  info: '#F0F0E8',
  link: '#FCCC0C'
} as const;

export const SPACING = { xs: 4, sm: 8, smMd: 12, md: 16, lg: 24, xl: 32, xxl: 48 } as const;

export const LAYOUT = {
  screenHorizontalMargin: 24,
  contentPadding: 24,
  gridGutter: 12,
  cardAspectRatio: 1.3333333333333333,
  safeAreaTopInsetMin: 16,
  safeAreaBottomInsetMin: 16
} as const;

export const TOUCH_TARGET = { min: 44, watch: 32 } as const;
