/**
 * Custom Style Dictionary format for the design-token primitives (Story 16.4).
 *
 * This lives under `scripts/` (not in `style-dictionary.config.mjs`) so the
 * token-formatting logic is covered by ESLint — root `*.config.mjs` files are in
 * the linter's ignore list. Importing this module registers the
 * `typescript/mlc-token-primitives` format as a side effect.
 *
 * The format reproduces the exact hand-authored primitive shapes: one
 * `export const <GROUP> = { … } as const` per top-level token group, with keys
 * and values passed through verbatim (no name/value transforms) so the generated
 * constants stay byte-stable. `scripts/build-tokens.mjs` prettier-formats the
 * output before writing/diffing.
 */
import StyleDictionary from 'style-dictionary';

export const CUSTOM_TS_FORMAT = 'typescript/mlc-token-primitives';

const HEADER = `/**
 * DO NOT EDIT — generated by Style Dictionary from the DTCG token JSON in tokens/.
 * Run \`yarn tokens:build\` to regenerate; \`yarn tokens:check\` guards against drift.
 * Canonical token values live in tokens/*.json (Story 16.4).
 */`;

// A processed Style Dictionary leaf carries a `path` array and a value; token
// groups are plain nested objects. This distinguishes the two while walking.
const isToken = (node) =>
  node !== null &&
  typeof node === 'object' &&
  Array.isArray(node.path) &&
  ('value' in node || '$value' in node);

const tokenValue = (node) => (node.value !== undefined ? node.value : node.$value);

const formatKey = (key) => {
  // Digit-only keys stay unquoted (e.g. `50`) only when they round-trip through
  // Number() — this rejects leading-zero keys like `007` that would otherwise
  // emit an illegal octal literal.
  if (/^\d+$/.test(key) && String(Number(key)) === key) return key;
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
};

// Numbers are emitted as numeric literals; every other JSON value goes through
// JSON.stringify (strings become quoted — Prettier later normalizes to single
// quotes; booleans/null render as bare literals, which is correct for TS).
const formatValue = (value) => (typeof value === 'number' ? String(value) : JSON.stringify(value));

const buildLiteral = (node) => {
  if (isToken(node)) return formatValue(tokenValue(node));
  // NOTE: integer-like keys are emitted in JS ascending-numeric order (engine
  // semantics), not source order — fine for ascending ramps like 50…900, but a
  // future out-of-order numeric key would be reordered here.
  const body = Object.keys(node)
    .filter((key) => !key.startsWith('$'))
    .map((key) => `${formatKey(key)}: ${buildLiteral(node[key])}`)
    .join(', ');
  return `{ ${body} }`;
};

StyleDictionary.registerFormat({
  name: CUSTOM_TS_FORMAT,
  format: ({ dictionary }) => {
    const groups = Object.keys(dictionary.tokens)
      .filter((name) => !name.startsWith('$'))
      .map((name) => `export const ${name} = ${buildLiteral(dictionary.tokens[name])} as const;`)
      .join('\n\n');
    return `${HEADER}\n\n${groups}\n`;
  }
});
