/*
 * Settings for the standalone Wear OS Gradle build.
 *
 * This project is DELIBERATELY not part of the React Native app's Gradle build.
 * `android/` is gitignored and regenerated by `expo prebuild`, so nothing here
 * may live inside it. A Wear OS app ships as its own APK anyway (AGP 9.0 even
 * removed the old `wearApp` embedding configurations), so there is nothing to
 * inject and no Expo config plugin is required. See ../watch-android/README.md.
 */
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    // Fail loudly if a subproject ever declares its own repositories, so the
    // dependency sources for this build stay auditable from this one file.
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "myLoyaltyCardsWear"

include(":app")
